### ISSUE TITLE
Improve color palette consistency of documentation

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#4134]
> I was wondering if someone had designed a "complete" color palette.

I'm pretty sure not, but happy to have a play around with it at some point, maybe not now though and when this is merged: https://github.com/pandas-dev/pydata-sphinx-theme/issues/138

_Originally posted by @chrisjsewell in https://github.com/aiidateam/aiida-core/pull/4129#issuecomment-636018850_

**Comment by chrisjsewell** [comment]
I think @greschd volunteered 😆

**Comment by chrisjsewell** [comment]
I'm just going to pop these here for now, but there are a few other issues I've made upstream regarding the documentation theme:

- [ ] pandas-dev/pydata-sphinx-theme#146
- [ ] pandas-dev/pydata-sphinx-theme#193
- [ ] pandas-dev/pydata-sphinx-theme#194
