### ISSUE TITLE
Docs: Complete "Topics: data types" section

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#4529]
So far, we've moved the previous content from the documentation on data types to the Topics section (#4469) and added some examples for most of the data types. However, there are still several data types which are currently not discussed in this section. 

#### TODO

- [ ] Add `Code` data type.
- [ ] Add `OrbitalData` data type.
- [ ] Add `ProjectionData` data type.
- [ ] Add `CifData` data type.
- [ ] Give whole section another good pass.
