### ISSUE TITLE
General improvements to usability

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#5816]
## Description

One of the main goals now that AiiDA v2.0.0 is released should be to identify and improve issues with the usability of AiiDA.

Some examples:

- improve cmdline to do common operations (e.g. library of common queries?)
- Making it easier to install computers/codes.
- document better how to facilitate certain queries (e.g. how to organize your nodes, use groups vs. extras, query for them easily and efficiently, ...)
- ...

## Tasks

- [x] Open project on `aiida-core`.
- [ ] Triage open issues into project.
- [x] Identify new UX issues by contacting users (informally and formally).

## Summary of hackathon usability discussion 

We have a usability improvement discussion during the plugin hackathon on 22nd Nov 2022. Plugin developers gave many constructive advice and feature requirements on how to improve usability. 

- [ ] The query builder is powerful but not easy (maybe over functional) for beginners to quickly build a query.
- [ ] Simplify the "How to guides" with fewer details and easy to follow.
- [ ] Provide python APIs for more verdi commands
- [ ] The verdi code does not fully mirror the deprecated verdi code setup, the code type has to be suffixed to using the –config.
- [ ] Update the [FAQ](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/faq.html) with adding a section with more common use cases. 
- [ ] Add notebook tests for querybuild example to make sure all the query examples in the documentation work.
- [ ] Uniform the discussion platform to one center rather than many places that users don't know where to post their questions.

**Comment by unkcpz** [comment]
I personally think that the platform for more general discussions and issues is critical since I also find sometimes don't know where to ask the questions. 
In the discussion, @danielhollas mention the discourse which become the gathering center of many big open-source project (such as, Julia, Python, twitter developers.. ) can be a good alternative to what we have now, the hybrid square of mailing list + github discussion + github issues + slack.

**Comment by danielhollas** [comment]
> I personally think that the platform for more general discussions and issues is critical since I also find sometimes don't know where to ask the questions.

I think this deserves it's own issue, or maybe rather an AEP. I am happy to contribute my opinions and knowledge of Discourse. (I am a Discourse admin and in another community project I drove the migration from mailing list to Discourse so I am aware of some of the possible pitfalls)

Couple crucial points:
 - Solution must be indexable by Google (e.g. not Slack)
 - Discourse (unless something changed) offers free hosting for open source projects. Also the advantage is that it is open source, so at any point we can take our data from hosted solution and host it ourselves. In other words, unlike in Slack or Github Discussions, we'd be fully in control, and thus have a more permanent record of discussions.
 - For fans of mailing lists, Dicourse supports the so called "Mailing list mode", so you could keep just using email. :-)
-  Discourse is great for async communication, and unlike Github discussion also supports private messages. I think they also have plugins for real time chat, but for that Slack might still be better (e.g. for hackatons / summer schools).

**Comment by unkcpz** [comment]
> I think this deserves it's own issue, or maybe rather an AEP. I am happy to contribute my opinions and knowledge of Discourse.

@danielhollas that'll be super great! Feel free to open the issue and I'll update this one and link to it. AEP is more than welcome. Thanks a lot!

**Comment by mbercx** [comment]
@unkcpz thanks for opening the issue and writing down the notes! I've already opened a (very basic) project re usability:

https://github.com/orgs/aiidateam/projects/4

Still a lot of triaging work to be done for sure, and we should also try and define what qualifies an issue to be added here.

**Comment by sphuber** [comment]
Since we have the team project to index usability improvements and the Discourse platform is now the accepted discussion forum, I am closing this issue.
