### ISSUE TITLE
SQLite backend often raises `Database is locked` when dealing with multiple processes

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#6532]
### Describe the bug

As also discussed in this [Discourse thread](https://aiida.discourse.group/t/getting-database-is-locked-error/432), when submitting several work chains with a SQLite backend (in this case with a RMQ daemon, but one could probably reproduce the same also without), one gets many errors of the type:
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE db_dbsetting SET val=?, time=? WHERE db_dbsetting.“key” = ?]
[parameters: (‘“2024-07-16T17:14:33.810058+02:00”’, ‘2024-07-16 17:14:33.810624’, ‘process|state_change|calculation’)]
(Background on this error at: [Error Messages — SQLAlchemy 2.0 Documentation](https://sqlalche.me/e/20/e3q8))
```

### Steps to reproduce
Probably just setup a profile and submit many work chains. I provide below, in the discussion, a simplified code that reproduces the issue.

### Expected behavior

We do not want jobs to except because of SQLite limitations. In the best case, they do not except. In the worst case scenario, we should clearly explain to users the limitations of the SQLite backend, and prevent processes excepting, but just limit the functionality of the backend in a "nice" way.

### Your environment
- aiida-core version: development version (2.6.1)

### Additional context
I summarize part of what I wrote on Discourse, plus some additional comments after our team discussion and further testing.

The `process|state_change|calculation` (in the DbSetting table) stores the last time a process changed state.
This is always done by the engine, even if not running with the daemon. The main (only?) place where this is used is at the end of `verdi process list`, so a user might quickly realize if the daemon is not running.

Since this is not a crucial feature, my suggestion is to drop this feature for the SQLite backend.
This can be implemented, e.g., with a backend class attribute that defines which features we support, e.g. `backend.store_last_process_change = False` in SQLite. (but of course other ways to do it are possible).

Then, if this flag is False, the engine does not attempt to store the state change.
Essentially, this would need to be implemented only [here](https://github.com/aiidateam/aiida-core/blob/a610460572f2d85435dfa850fdc247e1c666ef68/src/aiida/engine/utils.py#L262).

Then, to make it more clear to the user, we should also probably change the text provided by `verdi process list` to print something like “With SQLite, the last state change is not reported.”
Probably this can actually be mostly centralized [here](https://github.com/aiidateam/aiida-core/blob/a610460572f2d85435dfa850fdc247e1c666ef68/src/aiida/cmdline/utils/common.py#L83).

Finally, very importantly, we need to document the list of limitations in the docs (I don’t remember if we already have a page with the comparison of the backends, if not we should create it), listing all known limitations of each backend.

#### Why this is probably enough to solve most common concurrency issues
SQLite is clever. We are using a WAL (journaled) mode. Then, as [the SQLite docs state](https://www.sqlite.org/cgi/src/doc/begin-concurrent/doc/begin_concurrent.md), 

> Usually, SQLite allows at most one writer to proceed concurrently. The BEGIN CONCURRENT enhancement allows multiple writers to process write transactions simultanously if the database is in "wal" or "wal2" mode, although the system still serializes COMMIT commands.
> When a write-transaction is opened with "BEGIN CONCURRENT", actually locking the database is deferred until a COMMIT is executed. This means that any number of transactions started with BEGIN CONCURRENT may proceed concurrently. The system uses optimistic page-level-locking to prevent conflicting concurrent transactions from being committed.
> When a BEGIN CONCURRENT transaction is committed, the system checks whether or not any of the database pages that the transaction has read have been modified since the BEGIN CONCURRENT was opened. In other words - it asks if the transaction being committed operates on a different set of data than all other concurrently executing transactions. If the answer is "yes, this transaction did not read or modify any data modified by any concurrent transaction", then the transaction is committed as normal. Otherwise, if the transaction does conflict, it cannot be committed and an SQLITE_BUSY_SNAPSHOT error is returned. At this point, all the client can do is ROLLBACK the transaction.

In most cases, when submitting many calculations/workflows, each will either work on its own Node, or add new nodes. So the concurrent writes access different data blocks in the DB, and no concurrency issue is generated (probably if one really submits a lot, things get slow and one could get into similar problems, but we can clearly say that SQLite is not designed for high-throughput).

However, instead, the global "last timestamp" is actually a replacement of the same DB row in `DbSetting`. Therefore, this will in most cases lead to the exception discussed above.

#### Proof of concept
This simple set of scripts below demonstrate this (@sphuber pinging you as you asked about this earlier)

##### Check that storing many nodes, even concurrently, is OK
Content of file `test-many-node-storage.py`:
```python
import sys
from aiida.orm import Int
print(sys.argv[1], Int(value=1).store())
```
that can be submitted with the following bash script:
```bash
#!/bin/bash
for i in `seq 40`
do
    echo "Launching $i..."
    verdi run test-many-node-storage.py $i &
done
wait
```
Running with, e.g. `./run-many-node-storage.sh | grep uuid | wc -l` does not raise any exception, and all 40 scripts return correctly.

##### Check that storing a global variable creates concurrency issues
This is what happens internally, generating the exception discussed above.

Content of file `test-many-global-variable.py`:
```python
import sys
from aiida.manage import get_manager
from aiida.common import timezone
backend = get_manager().get_profile_storage()
backend.set_global_variable('process|state_change|calculation', timezone.now().isoformat(), 'The last time a process of type calculation, changed state')
print(sys.argv[1], "POST", backend.get_global_variable('process|state_change|calculation'))
```
that can be run with the following bash script:
```bash
#!/bin/bash
for i in `seq 40`
do
    echo "Launching $i..."
    verdi run test-many-global-variable.py $i &
done
wait
```
Running, e.g., `./run-many-global-variable.sh | grep POST  | wc -l` only works in my computer ~21-24 times out of 40, and displays a lot of exceptions of the type shown above for the rest.

```[tasklist]
### Tasks
- [ ] Disable selectively the action of `set_process_state_change_timestamp` on SQLite backends
- [ ] Change the behaviour of `print_last_process_state_change` (or directly of `verdi process list`) to show a message that says 'no last state change tracked for SQLite backends'
- [ ] Create (or extend) the page describing pros and cons of the various backends, and add the limitation of the process state change not being tracked (togehter with others, e.g. some queries with CONTAIN etc. do not work on SQLite)
```

**Comment by sphuber** [comment]
> Since this is not a crucial feature, my suggestion is to drop this feature for the SQLite backend.
This can be implemented, e.g., with a backend class attribute that defines which features we support, e.g. backend.store_last_process_change = False in SQLite. (but of course other ways to do it are possible).

As mentioned during the discussion, why, instead of dropping it entirely, not just catch the exception, log it and move on? Since the cause of the exception is that we are updating the last process change timestamp too often, skipping one because someone else is already updating, is not so bad. I opened PR #6534 that simply logs the failure in the `SqliteDosStorage` plugin and moves on. Is there a problem with that approach?

**Comment by giovannipizzi** [comment]
Thanks! I think it's a good idea - did you try if your approach would solve the issue with my simple example above (probably using the timestamp functions rather than copying their internal code - I couldn't easily because I needed to pass a Process instance to the timestamp function, and I wasn't sure how to create an instance).

Also, thanks to @sphuber I report here the current link of the docs of the backends: https://aiida.readthedocs.io/projects/aiida-core/en/stable/topics/storage.html - I think we should add a note there (even if with your implementation, the limitation is much less strong).

The only catch could be performance, as these transactions are serialized, so if we really run a lot, having those still is more expensive than not (but maybe the overhead is minimal).

Also, we need to check if the transaction only includes the change of state in the DbSetting, or also other changes (e.g. changes to DbNode or similar). Otherwise, by ignoring, we also lose other data that was being committed in the same transaction.

**Comment by giovannipizzi** [comment]
Actually, after checking the two possible limitations, I am now realizing that with your implementation it's not even a limitation: if this exception happens, essentially the timestamp that would have saved is the same within milliseconds, probably. So, since we typically can be OK with a precisions of tens of seconds, I think it's not a limitation

**Comment by sphuber** [comment]
> Thanks! I think it's a good idea - did you try if your approach would solve the issue with my simple example above (probably using the timestamp functions rather than copying their internal code - I couldn't easily because I needed to pass a Process instance to the timestamp function, and I wasn't sure how to create an instance)

I ran your script and I could reproduce the problem and after my fix it ran through fine, just with a bunch of warnings of the write failing due to the database being locked:

![image](https://github.com/user-attachments/assets/020fbd83-2a93-4324-91f3-9de4808a6f8d)
